In [1]:
# Torch : the torch package contains data structures for multi-dimensional tensors
#.        and mathematical operations over these are defined.

In [2]:
import torch
import numpy as np

In [4]:
x = torch.empty(5,4)
print(x)

tensor([[2.1715e-18, 2.6951e-09, 5.2592e+22, 1.6409e-07],
        [6.7879e-07, 5.2896e-08, 2.1781e-04, 2.6080e+20],
        [1.0621e-05, 2.6580e-06, 2.1707e-18, 1.6678e+19],
        [7.0976e+22, 2.1715e-18, 4.2330e+21, 1.6534e+19],
        [1.1625e+27, 1.4580e-19, 7.1856e+22, 4.3605e+27]])


In [5]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [6]:
torch.zeros(2)

tensor([0., 0.])

In [7]:
torch.rand(5,6)

tensor([[0.9316, 0.2644, 0.8756, 0.2445, 0.0578, 0.0597],
        [0.4261, 0.7171, 0.7637, 0.5437, 0.9655, 0.4238],
        [0.0442, 0.4704, 0.7687, 0.6551, 0.4960, 0.1254],
        [0.7284, 0.8865, 0.7038, 0.0976, 0.1261, 0.5402],
        [0.6825, 0.4009, 0.5119, 0.3289, 0.9585, 0.9918]])

In [8]:
l = [13,4]
r = np.array([4, 56, 7])

In [9]:
torch.tensor(l)

tensor([13,  4])

In [10]:
torch.tensor(r)

tensor([ 4, 56,  7])

In [11]:
x.size()

torch.Size([5, 4])

In [12]:
type(x)

torch.Tensor

In [21]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

tensor([[0.8156, 0.9382],
        [0.4950, 0.5707]])
tensor([[0.8959, 0.1457],
        [0.9629, 0.2213]])


In [22]:
x + y

tensor([[1.7114, 1.0839],
        [1.4579, 0.7920]])

In [23]:
torch.add(x,y)

tensor([[1.7114, 1.0839],
        [1.4579, 0.7920]])

In [24]:
# y 에 x 를 더한다.
y.add(x)

tensor([[1.7114, 1.0839],
        [1.4579, 0.7920]])

In [25]:
y

tensor([[0.8959, 0.1457],
        [0.9629, 0.2213]])

In [26]:
# y 에 x를 더해서 y를 대체한다
y.add_(x)

tensor([[1.7114, 1.0839],
        [1.4579, 0.7920]])

In [29]:
y

tensor([[1.7114, 1.0839],
        [1.4579, 0.7920]])

In [30]:
# y 행렬에서의 (1,1) 추출
# (파이썬에서는 0 부터 시작 이므로 y는 (0,0), (0,1), (1,0), (1,1)로 구성 되어 있습니다.
y[1,1]

tensor(0.7920)

In [31]:
# 1열을 표현하는 방식
y[:, 1]

tensor([1.0839, 0.7920])

In [32]:
x = torch.rand(8,8)
print(x)

tensor([[0.0040, 0.0248, 0.1685, 0.6564, 0.4019, 0.3151, 0.7130, 0.6988],
        [0.2709, 0.3478, 0.5051, 0.1666, 0.1736, 0.1669, 0.7013, 0.0990],
        [0.9172, 0.3355, 0.3620, 0.2393, 0.6436, 0.4054, 0.2880, 0.3320],
        [0.5652, 0.8067, 0.0836, 0.7683, 0.4573, 0.3002, 0.2951, 0.8597],
        [0.8238, 0.2091, 0.0582, 0.1406, 0.1807, 0.8086, 0.5243, 0.6662],
        [0.6544, 0.2161, 0.5486, 0.0847, 0.3903, 0.4926, 0.9892, 0.2390],
        [0.3921, 0.9408, 0.3054, 0.4779, 0.4322, 0.7497, 0.5968, 0.7806],
        [0.2810, 0.3537, 0.5416, 0.3574, 0.9321, 0.4182, 0.9825, 0.2014]])


In [33]:
# view 함수 : 행렬을 변환 시킬 때 사용 -> CNN 구현 시 FCN 을 지나가기 전에 사용합니다.
x.view(64)   # 1열로 나열할 때 사용

tensor([0.0040, 0.0248, 0.1685, 0.6564, 0.4019, 0.3151, 0.7130, 0.6988, 0.2709,
        0.3478, 0.5051, 0.1666, 0.1736, 0.1669, 0.7013, 0.0990, 0.9172, 0.3355,
        0.3620, 0.2393, 0.6436, 0.4054, 0.2880, 0.3320, 0.5652, 0.8067, 0.0836,
        0.7683, 0.4573, 0.3002, 0.2951, 0.8597, 0.8238, 0.2091, 0.0582, 0.1406,
        0.1807, 0.8086, 0.5243, 0.6662, 0.6544, 0.2161, 0.5486, 0.0847, 0.3903,
        0.4926, 0.9892, 0.2390, 0.3921, 0.9408, 0.3054, 0.4779, 0.4322, 0.7497,
        0.5968, 0.7806, 0.2810, 0.3537, 0.5416, 0.3574, 0.9321, 0.4182, 0.9825,
        0.2014])

In [34]:
# 4 X 16 형태로 변경
x.view(4, 16)

tensor([[0.0040, 0.0248, 0.1685, 0.6564, 0.4019, 0.3151, 0.7130, 0.6988, 0.2709,
         0.3478, 0.5051, 0.1666, 0.1736, 0.1669, 0.7013, 0.0990],
        [0.9172, 0.3355, 0.3620, 0.2393, 0.6436, 0.4054, 0.2880, 0.3320, 0.5652,
         0.8067, 0.0836, 0.7683, 0.4573, 0.3002, 0.2951, 0.8597],
        [0.8238, 0.2091, 0.0582, 0.1406, 0.1807, 0.8086, 0.5243, 0.6662, 0.6544,
         0.2161, 0.5486, 0.0847, 0.3903, 0.4926, 0.9892, 0.2390],
        [0.3921, 0.9408, 0.3054, 0.4779, 0.4322, 0.7497, 0.5968, 0.7806, 0.2810,
         0.3537, 0.5416, 0.3574, 0.9321, 0.4182, 0.9825, 0.2014]])

In [35]:
# -1 사용시, 뒤에 고정 된 숫자의 나머지 값을 넣어준다고 생각해도 무방
x.view(-1, 16)   # (ex. 64 / 16 = 4 가 되는 것 처럼, -1 = 4 가 됨)

tensor([[0.0040, 0.0248, 0.1685, 0.6564, 0.4019, 0.3151, 0.7130, 0.6988, 0.2709,
         0.3478, 0.5051, 0.1666, 0.1736, 0.1669, 0.7013, 0.0990],
        [0.9172, 0.3355, 0.3620, 0.2393, 0.6436, 0.4054, 0.2880, 0.3320, 0.5652,
         0.8067, 0.0836, 0.7683, 0.4573, 0.3002, 0.2951, 0.8597],
        [0.8238, 0.2091, 0.0582, 0.1406, 0.1807, 0.8086, 0.5243, 0.6662, 0.6544,
         0.2161, 0.5486, 0.0847, 0.3903, 0.4926, 0.9892, 0.2390],
        [0.3921, 0.9408, 0.3054, 0.4779, 0.4322, 0.7497, 0.5968, 0.7806, 0.2810,
         0.3537, 0.5416, 0.3574, 0.9321, 0.4182, 0.9825, 0.2014]])

In [36]:
x.view(-1,4,4)

tensor([[[0.0040, 0.0248, 0.1685, 0.6564],
         [0.4019, 0.3151, 0.7130, 0.6988],
         [0.2709, 0.3478, 0.5051, 0.1666],
         [0.1736, 0.1669, 0.7013, 0.0990]],

        [[0.9172, 0.3355, 0.3620, 0.2393],
         [0.6436, 0.4054, 0.2880, 0.3320],
         [0.5652, 0.8067, 0.0836, 0.7683],
         [0.4573, 0.3002, 0.2951, 0.8597]],

        [[0.8238, 0.2091, 0.0582, 0.1406],
         [0.1807, 0.8086, 0.5243, 0.6662],
         [0.6544, 0.2161, 0.5486, 0.0847],
         [0.3903, 0.4926, 0.9892, 0.2390]],

        [[0.3921, 0.9408, 0.3054, 0.4779],
         [0.4322, 0.7497, 0.5968, 0.7806],
         [0.2810, 0.3537, 0.5416, 0.3574],
         [0.9321, 0.4182, 0.9825, 0.2014]]])

In [37]:
# torch.Tensor 에서 numpy 전환하는 방법
y = x.numpy()
print(y)

[[0.00395948 0.02481455 0.16853487 0.6564107  0.4018727  0.31510967
  0.71302104 0.6987897 ]
 [0.2708555  0.34782034 0.50506365 0.16661668 0.1736095  0.16687351
  0.7012712  0.0990122 ]
 [0.91717464 0.33551127 0.36202306 0.23927939 0.6435893  0.4054337
  0.28797042 0.33195353]
 [0.56524515 0.80670696 0.08360255 0.76831895 0.45732486 0.3002432
  0.29505062 0.8597198 ]
 [0.82378834 0.20908934 0.05818295 0.14061028 0.18072087 0.80864394
  0.52427346 0.6662438 ]
 [0.65437645 0.21610862 0.54862493 0.08474308 0.39029562 0.49260783
  0.9891572  0.23902261]
 [0.39206755 0.9408107  0.30544055 0.47785693 0.4321925  0.7496811
  0.5967789  0.7806187 ]
 [0.28096122 0.35369688 0.5416227  0.35741192 0.93214864 0.41816533
  0.982504   0.20139837]]


In [38]:
type(y)

numpy.ndarray

In [39]:
# item : (스칼라 일 때만 사용 가능한 함수, 즉 원소가 하나 일 때만 사용 가능)
x = torch.ones(1)

In [40]:
x

tensor([1.])

In [41]:
# loss function 값은 스칼라 값이므로, 그것을 추출할 때 사용
x.item()

1.0